name: CI

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  tests:
    name: Тесты на PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4', '8.5']
    env:
      PHP_VERSION: ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v4
      - run: make build
      - run: make install
      - run: make test

  static-analysis:
    name: PHPStan на PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.5']
    env:
      PHP_VERSION: ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v4
      - run: make build
      - run: make install
      - run: make phpstan

  code-style:
    name: PSR-12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build
      - run: make install
      - run: make cs
